services:
  # db:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: asistenciasQR
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  #     TZ: America/La_Paz
  #   volumes:
  #     - qr_postgres_dev_data:/var/lib/postgresql/data
  #   ports:
  #     - "${POSTGRES_PORT:-5433}:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d asistenciasQR"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  backend:
    build:
      context: .
      dockerfile: ./.infra/backend/prod/Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    environment:
      TZ: America/La_Paz
      PAYLOAD_ENCRYPTION_KEY: ${PAYLOAD_ENCRYPTION_KEY:-}
    ports:
      - "4015:4000"
    volumes:
      - ./logs/backend:/app/logs

  frontend:
    build:
      context: .
      dockerfile: ./.infra/frontend/prod/Dockerfile
      args:
        BACKEND_BASE_URL: ${FRONTEND_BACKEND_BASE_URL:-https://innovafuncionarioapi.cochabamba.bo}
        PAYLOAD_ENCRYPTION_KEY: ${PAYLOAD_ENCRYPTION_KEY:-}
    restart: unless-stopped
    
    ports:
      - "4016:80"
