services:
  # db:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: asistenciasQR
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  #     TZ: America/La_Paz
  #   volumes:
  #     - qr_postgres_dev_data:/var/lib/postgresql/data
  #   ports:
  #     - "${POSTGRES_PORT:-5433}:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d asistenciasQR"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  backend:
    build:
      context: .
      dockerfile: ./.infra/backend/dev/Dockerfile
    restart: unless-stopped
    
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/asistenciasQR?schema=public
      PORT: 3000
      QR_DYNAMIC_SECRET: ${QR_DYNAMIC_SECRET:-secreto-local-qr}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      TZ: America/La_Paz
    ports:
      - "4015:3000"

  frontend:
    build:
      context: .
      dockerfile: ./.infra/frontend/prod/Dockerfile
      
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4016:80"

